apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-logout
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 3
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 256Mi
  envFrom:
    - secret: sf-logout
  filesFrom:
    - secret: sf-logout
  ingresses:
    - "https://communitylogout.nav.no"
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  env:
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com/services/oauth2/token'
    - name: SF_INSTANCE # TODO remove dependency to crm-utilites
      value: PRODUCTION
    - name: SF_VERSION
      value: 'v57.0'
    - name: VAULT_INSTANCE
      value: GCP